---
title: "Who we are"
date: last-modified
date-format: long
comments: false
---

The Future Forest Ecosystems Centre is a brand new research-oriented
team at the Forest Carbon and Climate Services Branch of the Office of
the Chief Forester (BC Ministry of Forests).

Started in 2022, the FFEC has put together a team of researchers to
answer complex questions about the stability and resilience for British
Columbia's forests to the effects of ongoing climate change, drought,
pests and fire.

To answer these complex questions, we use a using a variety of
approaches from advanced statistical modelling to downscale climate
projections and complex ecological landscape simulation modelling, to
collecting and analysing dendrochronological data to investigate tree
and stand responses to climate warming and drought.

## Team profiles

+---------------------+------------------------------------------------+
| ![Colin             | **Team Lead**                                  |
| Mahony](https://i1. |                                                |
| rgstatic.net/ii/pro | [Dr Colin                                      |
| file.image/32722151 | Mahony](http                                   |
| 7537280-14550270970 | s://www.researchgate.net/profile/Colin-Mahony) |
| 98_Q512/Colin-Mahon |                                                |
| y.jpg){width="232"} | <!--TODO: add description-->                   |
+---------------------+------------------------------------------------+
| ![Xin               | **Manager**                                    |
| Y                   |                                                |
| uan](https://media. | [Xin Yuan,                                     |
| licdn.com/dms/image | MSc](https://ca.linkedin.com/in/yuanforestry)  |
| /C4D03AQGiHXTdpzG37 |                                                |
| Q/profile-displayph | <!--TODO: add description-->                   |
| oto-shrink_800_800/ |                                                |
| 0/1605076173925?e=2 |                                                |
| 147483647&v=beta&t= |                                                |
| ombeCSWhnD1ZXe1wLme |                                                |
| KXDhXTgenUbTRc0isjH |                                                |
| ZlBgE){width="232"} |                                                |
+---------------------+------------------------------------------------+
| ![Aseem             | [Dr                                            |
| Sha                 | ](https:/                                      |
| rma](https://media. | /www.researchgate.net/profile/Aseem-Sharma-2/r |
| licdn.com/dms/image | esearch)[Aseem](https://sites.google.com/view/ |
| /D5603AQFpfpM5PgwSq | aseemrajsharma/home)[Sharma](https://www.resea |
| g/profile-displayph | rchgate.net/profile/Aseem-Sharma-2/research) - |
| oto-shrink_200_200/ | Research Climatologist                         |
| 0/1685942917177?e=1 |                                                |
| 692835200&v=beta&t= | <!--TODO: add description-->                   |
| yXXrVA-Ts6slrlX5SvX |                                                |
| X-4oQdqM2GCR1YiqaW2 |                                                |
| Fi0kk){width="232"} |                                                |
+---------------------+------------------------------------------------+
| ![Ceres             | [Dr Ceres                                      |
| Barros](https://i1. | Barros](https:                                 |
| rgstatic.net/ii/pro | //www.researchgate.net/profile/Ceres-Barros) - |
| file.image/70510294 | Research Ecologist                             |
| 8093955-15451210517 |                                                |
| 89_Q512/Ceres-Barro | Ceres has a strong passion for understanding   |
| s.jpg){width="232"} | and predicting ecosystem resilience to         |
|                     | multiple disturbances. She has experience      |
|                     | using complex ecological simulation models to  |
|                     | explore fundamental and applied questions      |
|                     | related to ecosystem stability to climate      |
|                     | change, drought, fire, land-use changes and    |
|                     | permafrost thaw. Her research is also strongly |
|                     | focused on the development of integrated,      |
|                     | reusable and transparent modelling workflows   |
|                     | that can be used not only for research         |
|                     | purposes, but also to support and inform       |
|                     | end-users within and beyond the government.    |
|                     |                                                |
|                     | She earned her BSc in Biology from the         |
|                     | University of Lisbon, Portugal, and an MSc in  |
|                     | Ecology and Environmental Sustainability from  |
|                     | the University of Aberdeen, Scotland. She      |
|                     | later obtained her PhD in Biodiversity,        |
|                     | Ecology and Environment from the University of |
|                     | Grenoble Alps, France, was a post-doctoral     |
|                     | fellow and research associate at the           |
|                     | University of British Columbia.                |
|                     |                                                |
|                     | She currently acts as a committee member of    |
|                     | the [British Ecological Society Macroecology   |
|                     | SIG](https://                                  |
|                     | www.britishecologicalsociety.org/membership-co |
|                     | mmunity/special-interest-groups/macroecology/) |
|                     | and the [Response Diversity                    |
|                     | Network](https://responsediversityn            |
|                     | etwork.github.io/RDN-website/who-we-are.html), |
|                     | and is an Associate Editor for [Ecological     |
|                     | Solutions and                                  |
|                     | Evidence](https://besjourn                     |
|                     | als.onlinelibrary.wiley.com/journal/26888319). |
+---------------------+------------------------------------------------+
| ![Kiri              | [Kiri Daust,                                   |
| Daust](https://a    | B                                              |
| vatars.githubuserco | Sc](https://scholar.google.ca/citations?user=E |
| ntent.com/u/3407303 | 0ktabQAAAAJ&hl=en&inst=17001591832933267808) - |
| 8?v=4){width="232"} | Data Scientist                                 |
|                     |                                                |
|                     | <!--TODO: add description-->                   |
+---------------------+------------------------------------------------+
| ![Vanessa           | [Vanessa Comeau,                               |
| Comea               | MSc](https://w                                 |
| u](https://static.w | ww.ubctreeringlab.ca/members/vanessa-comeau) - |
| ixstatic.com/media/ | Research Ecologist                             |
| 06cf37_fa60f83b389b |                                                |
| 42cdb1d56a78cfd9448 | <!--TODO: add description-->                   |
| 7~mv2.jpg/v1/fill/w |                                                |
| _1382,h_1382,al_c,q |                                                |
| _85/Vanessa%20Comea |                                                |
| u.jpg){width="232"} |                                                |
+---------------------+------------------------------------------------+
| ![Vivek             | [Dr Vivek                                      |
| Sriva               | Srivastava](https://www.                       |
| stava](https://pope | researchgate.net/profile/Vivek-Srivastava-9) - |
| col.sites.olt.ubc.c | Data Scientist                                 |
| a/files/2022/06/Viv |                                                |
| ek_Srivastava_squar | <!--TODO: add description-->                   |
| e.png){width="232"} |                                                |
+---------------------+------------------------------------------------+
