---
title: "Aseem's Bio"
date: last-modified
date-format: long
comments: false
---

Aseem is a Research Climatologist at FFEC bringing his expertise as a hydro-climatologist to the team. He is interested in understanding how climate variability and atmospheric dynamics influence surface hydro-climatology, extreme climate events, and wildfires. Currently, his research work is focused on improving our understanding of how extreme weathers events occur and impact our forest, ecosystems, and communities. Previously he worked in research projects that investigated the role of atmospheric blocking on wildfires, lightning occurrences and wildfires, Atmospheric Rivers and their impacts on water resources,  climate change and their impacts, especially on the mountainous region of Himalayas and the Canadian Rockies, and climate change risk assessments. 

Aseem has worked as a Data Science Specialist at BC Ministry of Water, Land and Resource Stewardship and as a Postdoctoral Research Scientist at Canada Wildfire (Natural Resources Canada and the University of Alberta). Aseem earned his Ph.D. and master's degrees from the University of Northern British Columbia in Prince George, BC, with grant support from Global Water Future and the BC Real Estate Foundation. He has co-authored over a dozen peer-reviewed articles and has presented his work at many scientific conferences and community events. His publications can be accessed on his website:<a href='https://sites.google.com/view/aseemrajsharma/publications'> https://sites.google.com/view/aseemrajsharma/publications</a>.

Born and raised in Nepal, Aseem, along with his wife and two children, now calls Kamloops, BC, home finds joy in exploring the region's beautiful trails through hiking. Aseem can be contacted via email at <a href= 'mailto: Aseem.Sharma@gov.bc.ca'>Aseem.Sharma@gov.bc.ca</a> or through social media on <a href='https://www.linkedin.com/in/aseem-raj-sharma-9b4769193/'> LinkedIn</a>, <a href='https://twitter.com/natureaseem'> X (formally twitter) </a>.
