---
title: "Ceres's Bio"
date-format: long
comments: false
---

Ceres has a strong passion for understanding and predicting ecosystem
resilience to multiple disturbances. She has experience using complex
ecological simulation models to explore fundamental and applied
questions related to ecosystem stability to climate change, drought,
fire, land-use changes and permafrost thaw. Her research is also
strongly focused on the development of integrated, reusable and
transparent modelling workflows that can be used not only for research
purposes, but also to support and inform end-users within and beyond
government. She earned her BSc in Biology from the University of Lisbon,
Portugal, and an MSc in Ecology and Environmental Sustainability from
the University of Aberdeen, Scotland. She later obtained her PhD in
Biodiversity, Ecology and Environment from the University of Grenoble
Alps, France, and was a post-doctoral fellow and research associate at
the the University of British Columbia, Vancouver, Canada. 

Ceres is a Research Scientist at the Pacific Forestry Centre, Canadian
Forest Service and an Adjunt Professor at the University of British Columbia
and at Université Laval. 
She is also on the [British Ecological Society Macroecology
SIG](https://www.britishecologicalsociety.org/membership-community/special-interest-groups/macroecology/)
committee and on the [Response Diversity
Network](https://responsediversitynetwork.github.io/RDN-website/who-we-are.html)
committee, and is an Associate Editor for [Ecological Solutions and
Evidence](https://besjournals.onlinelibrary.wiley.com/journal/26888319).
