---
title: "Vivek's Bio"

date-format: long
comments: false
---

Vivek is a PhD graduate from the University of British Columbia and is
currently working with the BC Ministry of Forests as a Forest Health
Research Climatologist. He is also an Honorary Research Associate at the
University of British Columbia. He holds a bachelor's degree in
forestry, a master's degree in remote sensing and GIS and a Ph.D. in
Forest Ecology and Integrated Pest Management with specialization in
forest health, ecological modelling, data analysis, GIS and applied
machine learning. Vivek studies forest insect pests and develops
computer-based spatial- temporal pest risk mathematical models to help
detect and mitigate the spread of plant pests and diseases. His work
also includes building data pipelines to understand, predict, and manage
forest health factors, using existing forest health datasets and new
technologies. He supervises multiple projects and students and actively
presents his work on various scientific platforms. Vivek has received
multiple academic and scientific awards and has published over a dozen
peer-reviewed papers and is an Associate Editor for Management of
Biological Invasions. Vivek is excited about helping with efforts to
proactively manage key insect pests while developing tools and
techniques for assisting decision-making in managing natural resources.
