on:
  pull_request:
    types: [opened, synchronize, closed, reopened]
    branches:
      - main
      - master

  push:
    branches:
      - main
      - master

name: Quarto Publish

jobs:
  build-deploy:
    if: |
      !contains(github.event.commits[0].message, '[skip-ci]') ||
      (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::data.table
            any::httr
            any::kableExtra
            any::knitr
            any::Require
            any::rmarkdown

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}